// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockLentes.Data;

#nullable disable

namespace StockLentes.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20260918115558_PhysicalLensesAndPrescriptionSections")]
    partial class PhysicalLensesAndPrescriptionSections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("StockLentes.Models.LensFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockRuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockRuleId");

                    b.ToTable("LensFamilies");
                });

            modelBuilder.Entity("StockLentes.Models.LensOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalNumber")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderReviewReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OpticalStoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalHeaderJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OpticalStoreId", "ExternalNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StockLentes.Models.LensProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LensFamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LowStockHalfPairs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TracksStock")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LensFamilyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StockLentes.Models.OpticalStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDemo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OpticalStores");
                });

            modelBuilder.Entity("StockLentes.Models.OrderLens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Add100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Axis")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Base100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cylinder100")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eye")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("InterpretationNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LensOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalInputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalProductCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalProductName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("PairNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PairType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrescriptionGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawInputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedProductId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresUsedPrescription")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedBase100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SelectedStockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Sphere100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsedAdd100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsedAxis")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsedCylinder100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsedSphere100")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesActualGraduation")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedProductId");

                    b.HasIndex("LensOrderId", "PrescriptionGroupId", "Eye")
                        .IsUnique();

                    b.HasIndex("LensOrderId", "Eye", "PairType", "PairNumber");

                    b.ToTable("OrderLenses");
                });

            modelBuilder.Entity("StockLentes.Models.PrescriptionSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Axis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cylinder")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderLensId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sphere")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderLensId", "Section")
                        .IsUnique();

                    b.ToTable("PrescriptionSections");
                });

            modelBuilder.Entity("StockLentes.Models.StockBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Add100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Base100")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CombinationKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cylinder100")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LensProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityHalfPairs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sphere100")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LensProductId", "CombinationKey")
                        .IsUnique();

                    b.ToTable("Stock", t =>
                        {
                            t.HasCheckConstraint("CK_Stock_Nonnegative", "QuantityHalfPairs >= 0");
                        });
                });

            modelBuilder.Entity("StockLentes.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualAdd100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualAxis")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualBase100")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActualCylinder100")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualProductCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("ActualProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualProductName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ActualSphere100")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManualSelection")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderLensId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityHalfPairs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockAfterHalfPairs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockBalanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StockBeforeHalfPairs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuggestedBase100")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActualProductId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("OrderLensId")
                        .IsUnique();

                    b.HasIndex("StockBalanceId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("StockLentes.Models.StockRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsesAdd")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesBase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesCylinder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsesSphere")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StockRules");
                });

            modelBuilder.Entity("StockLentes.Models.LensFamily", b =>
                {
                    b.HasOne("StockLentes.Models.StockRule", "Rule")
                        .WithMany()
                        .HasForeignKey("StockRuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("StockLentes.Models.LensOrder", b =>
                {
                    b.HasOne("StockLentes.Models.OpticalStore", "Store")
                        .WithMany()
                        .HasForeignKey("OpticalStoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Store");
                });

            modelBuilder.Entity("StockLentes.Models.LensProduct", b =>
                {
                    b.HasOne("StockLentes.Models.LensFamily", "Family")
                        .WithMany()
                        .HasForeignKey("LensFamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("StockLentes.Models.OrderLens", b =>
                {
                    b.HasOne("StockLentes.Models.LensOrder", "Order")
                        .WithMany("Lenses")
                        .HasForeignKey("LensOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLentes.Models.LensProduct", "RequestedProduct")
                        .WithMany()
                        .HasForeignKey("RequestedProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("RequestedProduct");
                });

            modelBuilder.Entity("StockLentes.Models.PrescriptionSection", b =>
                {
                    b.HasOne("StockLentes.Models.OrderLens", "Lens")
                        .WithMany("PrescriptionSections")
                        .HasForeignKey("OrderLensId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lens");
                });

            modelBuilder.Entity("StockLentes.Models.StockBalance", b =>
                {
                    b.HasOne("StockLentes.Models.LensProduct", "Product")
                        .WithMany()
                        .HasForeignKey("LensProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockLentes.Models.StockMovement", b =>
                {
                    b.HasOne("StockLentes.Models.LensProduct", "ActualProduct")
                        .WithMany()
                        .HasForeignKey("ActualProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLentes.Models.OrderLens", "OrderLens")
                        .WithMany()
                        .HasForeignKey("OrderLensId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockLentes.Models.StockBalance", "Balance")
                        .WithMany()
                        .HasForeignKey("StockBalanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActualProduct");

                    b.Navigation("Balance");

                    b.Navigation("OrderLens");
                });

            modelBuilder.Entity("StockLentes.Models.LensOrder", b =>
                {
                    b.Navigation("Lenses");
                });

            modelBuilder.Entity("StockLentes.Models.OrderLens", b =>
                {
                    b.Navigation("PrescriptionSections");
                });
#pragma warning restore 612, 618
        }
    }
}
